// MENU ACTIONS
export const GET_MENU = "GET_MENU"
export const GET_MENU_SUCCESS = "GET_MENU_SUCCESS"
export const GET_MENU_FAIL = "GET_MENU_FAIL"

// CART ACTIONS
export const CLEAR_CART = "CLEAR_CART"
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART"
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART"

// ORDER ACTIONS
export const PLACE_ORDER = "PLACE_ORDER"
export const PLACE_ORDER_INIT = "PLACE_ORDER_INIT"
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS"
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL"

// AUTH ACTIONS
export const AUTH_CHANGED = "AUTH_CHANGED"
export const EMAIL_AUTH = "EMAIL_AUTH"
export const EMAIL_AUTH_FAIL = "EMAIL_AUTH_FAIL"
export const EMAIL_REGISTER = "EMAIL_REGISTER"
export const EMAIL_REGISTER_SUCCESS = "EMAIL_REGISTER_SUCCESS"
export const EMAIL_REGISTER_FAIL = "EMAIL_REGISTER_FAIL"

// ADDRESS ACTIONS
export const GET_ADDRESS = "GET_ADDRESS"
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS"
export const GET_ADDRESS_FAIL = "GET_ADDRESS_FAIL"
export const ADD_ADDRESS = "ADD_ADDRESS"
export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS"
export const ADD_ADDRESS_FAIL = "ADD_ADDRESS_FAIL"
export const CLEAR_ADDRESS = "CLEAR_ADDRESS"

// PAST ORDER ACTIONS
export const GET_ORDERS = "GET_ORDERS"
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS"
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL"
export const CLEAR_ORDERS = "CLEAR_ORDERS"